export enum TabId {
  User = 1,
  UserAccess = 2,
  Group = 3,
}

export const columnDefinition: any[] = [
  {
    tabId: TabId.User,
    columnId: 'userId',
    columnHeader: 'User Id',
    columnDataAlias: '',
    filterable: true,
    ngValue: '',
  },
  {
    tabId: TabId.User,
    columnId: 'firstName',
    columnHeader: 'First Name',
    columnDataAlias: '',
    filterable: true,
    ngValue: '',
  },
  {
    tabId: TabId.User,
    columnId: 'lastName',
    columnHeader: 'Last Name',
    columnDataAlias: '',
    filterable: true,
    ngValue: '',
  },
  {
    tabId: TabId.User,
    columnId: 'loginName',
    columnHeader: 'Login Name',
    columnDataAlias: '',
    filterable: true,
    ngValue: '',
  },
  {
    tabId: TabId.User,
    columnId: 'password',
    columnHeader: 'Password',
    columnDataAlias: '',
    filterable: false,
    ngValue: '',
  },
  {
    tabId: TabId.User,
    columnId: 'email',
    columnHeader: 'Email',
    columnDataAlias: '',
    filterable: true,
    ngValue: '',
  },
  {
    tabId: TabId.UserAccess,
    columnId: 'userId',
    columnHeader: 'User Id',
    columnDataAlias: '',
    filterable: true,
    ngValue: '',
  },
  {
    tabId: TabId.UserAccess,
    columnId: 'groupId',
    columnHeader: 'Group Id',
    columnDataAlias: '',
    filterable: true,
    ngValue: '',
  },
  {
    tabId: TabId.UserAccess,
    columnId: 'dateOfRelationshipCreation',
    columnHeader: 'Date of Relationship Creation',
    columnDataAlias: '',
    filterable: true,
    ngValue: '',
  },
  {
    tabId: TabId.Group,
    columnId: 'groupId',
    columnHeader: 'Group Id',
    columnDataAlias: '',
    filterable: true,
    ngValue: '',
  },
  {
    tabId: TabId.Group,
    columnId: 'groupName',
    columnHeader: 'Group Name',
    columnDataAlias: '',
    filterable: true,
    ngValue: '',
  },
  {
    tabId: TabId.Group,
    columnId: 'description',
    columnHeader: 'Description',
    columnDataAlias: '',
    filterable: true,
    ngValue: '',
  },
];
